export const products = [{
        id: 1,
        img: "earpods1.png",
        imgCart: "earpods1_cart.png",
        title: "Apple BYZ S852I",
        cost: 2927,
        costBefore: 3527,
        rate: 4.7,
        category: "earpods",
    },
    {
        id: 2,
        img: "earpods2.png",
        imgCart: "",
        title: "Apple EarPods",
        cost: 2327,
        costBefore: "",
        rate: 4.5,
        category: "earpods",
    },
    {
        id: 3,
        img: "earpods3.png",
        imgCart: "",
        title: "Apple EarPods",
        cost: 2327,
        costBefore: "",
        rate: 4.5,
        category: "earpods",
    },
    {
        id: 4,
        img: "earpods1.png",
        imgCart: "earpods1_cart.png",
        title: "Apple BYZ S852I",
        cost: 2927,
        costBefore: "",
        rate: 4.7,
        category: "earpods",
    },
    {
        id: 5,
        img: "earpods2.png",
        imgCart: "",
        title: "Apple EarPods",
        cost: 2327,
        costBefore: "",
        rate: 4.5,
        category: "earpods",
    },
    {
        id: 6,
        img: "earpods3.png",
        imgCart: "",
        title: "Apple EarPods",
        cost: 2327,
        costBefore: "",
        rate: 4.5,
        category: "earpods",
    },
    {
        id: 7,
        img: "airpods1.png",
        imgCart: "",
        title: "Apple AirPods",
        cost: 9527,
        costBefore: "",
        rate: 4.7,
        category: "wireless",
    },
    {
        id: 8,
        img: "airpods2.png",
        imgCart: "",
        title: "GERLAX GH-04",
        cost: 6527,
        costBefore: "",
        rate: 4.7,
        category: "wireless",
    },
    {
        id: 9,
        img: "airpods3.png",
        imgCart: "",
        title: "BOROFONE BO4",
        cost: 7527,
        costBefore: "",
        rate: 4.7,
        category: "wireless",
    }
];